service: aoc-slackbot

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2

functions:
  bot:
    handler: handler.run
    events:
      - schedule: cron(1 * * * ? *)
    environment:
      LEADERBOARD_ID: "${env:LEADERBOARD_ID}"
      LEADERBOARD_SESSION: "${env:LEADERBOARD_SESSION}"
      SLACK_WEBHOOK: "${env:SLACK_WEBHOOK}"
      LEADERBOARD_TEAMS: "${env:LEADERBOARD_TEAMS}"
      LEADERBOARD_USE_LOCAL: "${env:LEADERBOARD_USE_LOCAL}"
      INTERVAL_HOURS: "${env:INTERVAL_HOURS}"

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
